import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/** Writes the plugin's public Java registration class. The JNI glue binds its native method. */
@CacheableTask
abstract class GenerateRegistrationClass : DefaultTask() {
    @get:Input abstract val qualifiedClassName: Property<String>
    @get:Input abstract val pluginId: Property<String>
    @get:Input abstract val pluginVersion: Property<String>
    @get:Input abstract val displayName: Property<String>
    @get:Input abstract val libraryName: Property<String>
    @get:OutputDirectory abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val qualified = qualifiedClassName.get()
        val packageName = qualified.substringBeforeLast('.')
        val className = qualified.substringAfterLast('.')
        val directory = outputDirectory.get().asFile.resolve(packageName.replace('.', '/'))
        directory.deleteRecursively()
        directory.mkdirs()
        directory.resolve("$className.java").writeText(
            """
            |// Generated by maplibre-native-plugins. Do not edit.
            |package $packageName;
            |
            |import org.maplibre.android.LibraryLoader;
            |
            |/** Registers the ${displayName.get().javadoc()} plugin with MapLibre Native. */
            |public final class $className {
            |  /** The plugin identifier from plugin.json. */
            |  public static final String ID = ${pluginId.get().javaString()};
            |  /** The plugin version from plugin.json. */
            |  public static final String VERSION = ${pluginVersion.get().javaString()};
            |
            |  private static boolean nativeLoaded;
            |
            |  private $className() {}
            |
            |  /**
            |   * Registers the plugin's layer types. Call after {@code MapLibre.getInstance} and before
            |   * loading a style that uses them. Repeated calls succeed without registering again.
            |   *
            |   * @throws IllegalStateException if MapLibre rejects the plugin
            |   */
            |  public static synchronized void register() {
            |    // The MapLibre renderer library exports mln_plugin_register_v1; make sure it is loaded.
            |    LibraryLoader.load();
            |    if (!nativeLoaded) {
            |      // Plugins keep native callbacks for the process lifetime and are never unloaded.
            |      System.loadLibrary(${libraryName.get().javaString()});
            |      nativeLoaded = true;
            |    }
            |    String[] message = new String[1];
            |    int status = nativeRegister(message);
            |    // MLN_PLUGIN_STATUS_OK or MLN_PLUGIN_STATUS_ALREADY_REGISTERED
            |    if (status == 0 || status == 1) return;
            |    throw new IllegalStateException(
            |        "Could not register plugin " + ID + " (status " + status + "): " + message[0]);
            |  }
            |
            |  private static native int nativeRegister(String[] message);
            |}
            |""".trimMargin()
        )
    }

    private fun String.javaString(): String =
        "\"" + replace("\\", "\\\\").replace("\"", "\\\"") + "\""

    private fun String.javadoc(): String = replace("*/", "*&#47;").replace("<", "&lt;")
}
